# Travis build integration.
# https://docs.travis-ci.com/
language: cpp

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - gcc-4.8
      - g++-4.8
      - libcurl4-openssl-dev

env:
  global:
    - secure: "TODO"

# TODO: Add an OS X config.
matrix:
  include:
    - os: linux
      compiler: gcc
      env: USE_CC=gcc-4.8 USE_CXX=g++-4.8 COVERITY_SCAN=true
    - os: linux
      compiler: clang

before_install: ./scripts/travis-checkout.sh
script: ./scripts/travis-build.sh
